#!/bin/bash

WORKSPACE_PATHS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export WRODERI_REPO_ROOT="${WRODERI_REPO_ROOT:-$WORKSPACE_PATHS_DIR}"
export WRODERI_PROJECT_ROOT="${WRODERI_PROJECT_ROOT:-$(cd "$WRODERI_REPO_ROOT/.." && pwd)}"
export WRODERI_SCRATCH_ROOT="${WRODERI_SCRATCH_ROOT:-$WRODERI_REPO_ROOT/scratch}"
export WRODERI_MODELS_ROOT="${WRODERI_MODELS_ROOT:-$WRODERI_REPO_ROOT/models}"
